UPDATE restaurants SET image_url = 'images_1/idli.webp' WHERE id=1;
UPDATE restaurants SET image_url = 'images_1/MasalaDosa.webp' WHERE id=2;
UPDATE restaurants SET image_url = 'images_1/0_Pasta.png' WHERE id=3;
UPDATE restaurants SET image_url = 'images_1/Green.jpg' WHERE id=4;
UPDATE restaurants SET image_url = 'images_1/Uttapam.jpg' WHERE id=5;
UPDATE restaurants SET image_url = 'images_1/vada.jpg' WHERE id=6;
UPDATE restaurants SET image_url = 'images_1/spicegarden.webp' WHERE id=7;
UPDATE restaurants SET image_url = 'Images_2/15 idli vada.jpeg' WHERE id=8;
UPDATE restaurants SET image_url = 'Images_2/15 masala dosa.jpeg' WHERE id=9;
UPDATE restaurants SET image_url = 'images_1/Arrabbiata.webp' WHERE id=10;
UPDATE restaurants SET image_url = 'images_1/spicegarden.webp' WHERE id=11;
UPDATE restaurants SET image_url = 'Images_2/15 meals.jpeg' WHERE id=12;
UPDATE restaurants SET image_url = 'images_1/background.webp' WHERE id=13;
UPDATE restaurants SET image_url = 'images_1/biriyanihouse.webp' WHERE id=14;
UPDATE restaurants SET image_url = 'images_1/Baklava.jpg' WHERE id=15;
UPDATE restaurants SET image_url = 'images_1/Bangkokexpress.webp' WHERE id=16;
UPDATE restaurants SET image_url = 'images_1/blueberrymuffin.jpg' WHERE id=17;
UPDATE restaurants SET image_url = 'images_1/Chicken-Biryani.webp' WHERE id=18;
UPDATE restaurants SET image_url = 'images_1/BBQchickenpizza.jpg' WHERE id=19;
UPDATE restaurants SET image_url = 'images_1/Chicken-Biryani.webp' WHERE id=20;
UPDATE restaurants SET image_url = 'Images_2/empire_rest.avif' WHERE id=21;
UPDATE restaurants SET image_url = 'images_1/Biryani.jpg' WHERE id=22;
UPDATE restaurants SET image_url = 'images_1/cafe.jpg' WHERE id=23;
UPDATE restaurants SET image_url = 'images_1/cap.webp' WHERE id=24;
UPDATE restaurants SET image_url = 'images_1/butterchicken.webp' WHERE id=25;
UPDATE restaurants SET image_url = 'images_1/coastalcurry.jpg' WHERE id=26;
UPDATE restaurants SET image_url = 'images_1/Muttonbiryani.webp' WHERE id=27;
UPDATE restaurants SET image_url = 'images_1/croissants.jpg' WHERE id=28;
UPDATE restaurants SET image_url = 'images_1/Dragonpalace.webp' WHERE id=29;
UPDATE restaurants SET image_url = 'images_1/biriyanihouse.webp' WHERE id=30;
UPDATE restaurants SET image_url = 'images_1/Falafel.jpg' WHERE id=31;
UPDATE restaurants SET image_url = 'images_1/Biryani.jpg' WHERE id=32;
UPDATE restaurants SET image_url = 'images_1/Biryani.jpg' WHERE id=33;
UPDATE restaurants SET image_url = 'images_1/Biryani.jpg' WHERE id=34;
UPDATE restaurants SET image_url = 'images_1/Biryani.jpg' WHERE id=35;
UPDATE restaurants SET image_url = 'images_1/Biryani.jpg' WHERE id=36;
UPDATE restaurants SET image_url = 'images_1/Biryani.jpg' WHERE id=37;
UPDATE restaurants SET image_url = 'images_1/Biryani.jpg' WHERE id=38;
UPDATE restaurants SET image_url = 'images_1/Biryani.jpg' WHERE id=39;
UPDATE restaurants SET image_url = 'images_1/Biryani.jpg' WHERE id=40;
UPDATE restaurants SET image_url = 'images_1/Biryani.jpg' WHERE id=41;
UPDATE restaurants SET image_url = 'images_1/Biryani.jpg' WHERE id=42;
UPDATE restaurants SET image_url = 'images_1/Biryani.jpg' WHERE id=43;
UPDATE restaurants SET image_url = 'images_1/Biryani.jpg' WHERE id=44;
UPDATE restaurants SET image_url = 'images_1/Biryani.jpg' WHERE id=45;
UPDATE restaurants SET image_url = 'images_1/chickenburger.jpg' WHERE id=46;
UPDATE restaurants SET image_url = 'images_1/ChickenCurry.jpg' WHERE id=47;
UPDATE restaurants SET image_url = 'images_1/Dragonpalace.webp' WHERE id=48;
UPDATE restaurants SET image_url = 'images_1/friedrice.jpg' WHERE id=49;
UPDATE restaurants SET image_url = 'images_1/chilli-chicken.jpg' WHERE id=50;
UPDATE restaurants SET image_url = 'images_1/biriyanihouse.webp' WHERE id=51;
UPDATE restaurants SET image_url = 'images_1/Fishtikka.jpg' WHERE id=52;
UPDATE restaurants SET image_url = 'images_1/kebab.webp' WHERE id=53;
UPDATE restaurants SET image_url = 'images_1/kebab1.webp' WHERE id=54;
UPDATE restaurants SET image_url = 'images_1/froosty.jpg' WHERE id=55;
UPDATE restaurants SET image_url = 'images_1/MasalaDosa.webp' WHERE id=56;
UPDATE restaurants SET image_url = 'images_1/garlicbread.jpg' WHERE id=57;
UPDATE restaurants SET image_url = 'images_1/MasalaDosa.webp' WHERE id=58;
UPDATE restaurants SET image_url = 'images_1/GreekSalad.jpg' WHERE id=59;
UPDATE restaurants SET image_url = 'images_1/GreenCurry.jpg' WHERE id=60;
UPDATE restaurants SET image_url = 'images_gen/luxury_restaurant_1787916510173.jpg' WHERE id=61;
UPDATE restaurants SET image_url = 'images_1/biriyanihouse.webp' WHERE id=62;
UPDATE restaurants SET image_url = 'Images_2/15 meals.jpeg' WHERE id=63;
UPDATE restaurants SET image_url = 'images_1/hakkanoodles.jpg' WHERE id=64;
UPDATE restaurants SET image_url = 'images_1/hummus.jpg' WHERE id=65;
UPDATE restaurants SET image_url = 'images_1/ice.jpg' WHERE id=66;
UPDATE restaurants SET image_url = 'images_1/kheer.jpg' WHERE id=67;
UPDATE restaurants SET image_url = 'images_1/Fishtikka.jpg' WHERE id=68;
UPDATE restaurants SET image_url = 'images_1/Fishtikka.jpg' WHERE id=69;
UPDATE restaurants SET image_url = 'images_1/coastalcurry.jpg' WHERE id=70;
UPDATE restaurants SET image_url = 'images_gen/seafood_pasta_1787916394557.jpg' WHERE id=71;
UPDATE restaurants SET image_url = 'images_1/Fishtikka.jpg' WHERE id=72;
UPDATE restaurants SET image_url = 'images_gen/seafood_pasta_1787916394557.jpg' WHERE id=73;
UPDATE restaurants SET image_url = 'images_gen/seafood_pasta_1787916394557.jpg' WHERE id=74;
UPDATE restaurants SET image_url = 'images_1/amritsarifish.jpg' WHERE id=75;
UPDATE restaurants SET image_url = 'images_1/BBQchickenpizza.jpg' WHERE id=76;
UPDATE restaurants SET image_url = 'images_1/BBQchickenpizza.jpg' WHERE id=77;
UPDATE restaurants SET image_url = 'images_1/BBQchickenpizza.jpg' WHERE id=78;
UPDATE restaurants SET image_url = 'images_1/BBQchickenpizza.jpg' WHERE id=79;
UPDATE restaurants SET image_url = 'images_1/BBQchickenpizza.jpg' WHERE id=80;
UPDATE restaurants SET image_url = 'images_1/BBQchickenpizza.jpg' WHERE id=81;
UPDATE restaurants SET image_url = 'images_1/BBQchickenpizza.jpg' WHERE id=82;
UPDATE restaurants SET image_url = 'images_1/Lasagna.jpg' WHERE id=83;
UPDATE restaurants SET image_url = 'images_1/lassi.jpg' WHERE id=84;
UPDATE restaurants SET image_url = 'images_1/BBQchickenpizza.jpg' WHERE id=85;
UPDATE restaurants SET image_url = 'images_1/makki.jpg' WHERE id=86;
UPDATE restaurants SET image_url = 'images_1/manchurian.jpg' WHERE id=87;
UPDATE restaurants SET image_url = 'images_1/chickenburger.jpg' WHERE id=88;
UPDATE restaurants SET image_url = 'Images_2/subway.avif' WHERE id=89;
UPDATE restaurants SET image_url = 'images_1/mango.jpg' WHERE id=90;
UPDATE restaurants SET image_url = 'images_1/springrolls.jpg' WHERE id=91;
UPDATE restaurants SET image_url = 'images_1/Milkshake.jpg' WHERE id=92;
UPDATE restaurants SET image_url = 'images_1/mangorice.webp' WHERE id=93;
UPDATE restaurants SET image_url = 'images_1/burgerbarn.jpg' WHERE id=94;
UPDATE restaurants SET image_url = 'Images_2/7 Tacos.jpeg' WHERE id=95;
UPDATE restaurants SET image_url = 'images_1/mediterranean.jpg' WHERE id=96;
UPDATE restaurants SET image_url = 'images_1/Meghanafoods.webp' WHERE id=97;
UPDATE restaurants SET image_url = 'images_1/Dragonpalace.webp' WHERE id=98;
UPDATE restaurants SET image_url = 'images_1/Meghanafoods.webp' WHERE id=99;
UPDATE restaurants SET image_url = 'images_1/Bangkokexpress.webp' WHERE id=100;
UPDATE menu SET image_url = 'images_1/idli.webp' WHERE restaurant_id=1 AND name='Idli (4 Pcs)';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=1 AND name='Ghee Roast Dosa';
UPDATE menu SET image_url = 'images_1/vada.jpg' WHERE restaurant_id=1 AND name='Medu Vada (2 Pcs)';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=1 AND name='Masala Dosa';
UPDATE menu SET image_url = 'images_1/Uttapam.jpg' WHERE restaurant_id=1 AND name='Pongal';
UPDATE menu SET image_url = 'images_1/coldcoffee.jpg' WHERE restaurant_id=1 AND name='Filter Coffee';
UPDATE menu SET image_url = 'Images_2/15 meals.jpeg' WHERE restaurant_id=2 AND name='Full Meals';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=2 AND name='Rava Dosa';
UPDATE menu SET image_url = 'images_1/Brownie.jpg' WHERE restaurant_id=2 AND name='Kesari';
UPDATE menu SET image_url = 'images_1/idli.webp' WHERE restaurant_id=2 AND name='Upma';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=2 AND name='Chapati with Kurma';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=2 AND name='Poori Masala';
UPDATE menu SET image_url = 'images_1/ChickenCurry.jpg' WHERE restaurant_id=3 AND name='Chettinad Vegetable Curry';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=3 AND name='Kara Kuzhambu';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=3 AND name='Paniyaram';
UPDATE menu SET image_url = 'images_gen/appam_stew_1787916343153.jpg' WHERE restaurant_id=3 AND name='Appam with Stew';
UPDATE menu SET image_url = 'Images_2/15 meals.jpeg' WHERE restaurant_id=3 AND name='Chettinad Full Meals';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=4 AND name='Paneer Butter Masala';
UPDATE menu SET image_url = 'images_1/DalMakhani.webp' WHERE restaurant_id=4 AND name='Dal Makhani';
UPDATE menu SET image_url = 'images_1/GarlicNaan.jpg' WHERE restaurant_id=4 AND name='Butter Naan';
UPDATE menu SET image_url = 'images_1/cholebature.webp' WHERE restaurant_id=4 AND name='Chole Bhature';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=4 AND name='Veg Biryani';
UPDATE menu SET image_url = 'images_1/gulabjamun.webp' WHERE restaurant_id=4 AND name='Gulab Jamun (2 Pcs)';
UPDATE menu SET image_url = 'images_1/idli.webp' WHERE restaurant_id=5 AND name='Ven Pongal';
UPDATE menu SET image_url = 'images_1/vada.jpg' WHERE restaurant_id=5 AND name='Sambar Vada';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=5 AND name='Onion Rava Dosa';
UPDATE menu SET image_url = 'Images_2/15 meals.jpeg' WHERE restaurant_id=5 AND name='Mini Meals';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=5 AND name='Bonda';
UPDATE menu SET image_url = 'Images_2/15 meals.jpeg' WHERE restaurant_id=6 AND name='Full Meals Thali';
UPDATE menu SET image_url = 'Images_2/2 chicken fried rice.jpeg' WHERE restaurant_id=6 AND name='Rasam Rice';
UPDATE menu SET image_url = 'Images_2/2 chicken fried rice.jpeg' WHERE restaurant_id=6 AND name='Curd Rice';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=6 AND name='Plain Dosa';
UPDATE menu SET image_url = 'images_gen/payasam_1787916358390.jpg' WHERE restaurant_id=6 AND name='Payasam';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=7 AND name='Caesar Salad';
UPDATE menu SET image_url = 'images_1/burgerbarn.jpg' WHERE restaurant_id=7 AND name='Veg Club Sandwich';
UPDATE menu SET image_url = 'images_1/chickenburger.jpg' WHERE restaurant_id=7 AND name='Garden Burger';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=7 AND name='Mushroom Pasta';
UPDATE menu SET image_url = 'Images_2/6 Paneer Bowl.jpeg' WHERE restaurant_id=7 AND name='Fresh Fruit Bowl';
UPDATE menu SET image_url = 'images_1/coldcoffee.jpg' WHERE restaurant_id=7 AND name='Cold Coffee';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=8 AND name='Kari Dosa';
UPDATE menu SET image_url = 'images_1/idli.webp' WHERE restaurant_id=8 AND name='Idli Sambar';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=8 AND name='Set Dosa (3 Pcs)';
UPDATE menu SET image_url = 'images_1/coldcoffee.jpg' WHERE restaurant_id=8 AND name='Filter Coffee';
UPDATE menu SET image_url = 'images_1/vada.jpg' WHERE restaurant_id=8 AND name='Upma with Vada';
UPDATE menu SET image_url = 'images_1/idli.webp' WHERE restaurant_id=9 AND name='Idli Vada Combo';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=9 AND name='Masala Vada';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=9 AND name='Paper Dosa';
UPDATE menu SET image_url = 'images_1/garlicbread.jpg' WHERE restaurant_id=9 AND name='Bread Omelette';
UPDATE menu SET image_url = 'images_1/matchaicecream.jpg' WHERE restaurant_id=9 AND name='Chai';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=10 AND name='Special Thali';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=10 AND name='Mini Thali';
UPDATE menu SET image_url = 'Images_2/2 chicken fried rice.jpeg' WHERE restaurant_id=10 AND name='Sambar Rice';
UPDATE menu SET image_url = 'Images_2/2 chicken fried rice.jpeg' WHERE restaurant_id=10 AND name='Lemon Rice';
UPDATE menu SET image_url = 'Images_2/2 chicken fried rice.jpeg' WHERE restaurant_id=10 AND name='Tamarind Rice';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=11 AND name='Udupi Masala Dosa';
UPDATE menu SET image_url = 'images_1/Uttapam.jpg' WHERE restaurant_id=11 AND name='Uttapam';
UPDATE menu SET image_url = 'images_1/idli.webp' WHERE restaurant_id=11 AND name='Rava Upma';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=11 AND name='Pesarattu';
UPDATE menu SET image_url = 'images_1/makki.jpg' WHERE restaurant_id=11 AND name='Akki Rotti';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=12 AND name='Rajma Chawal';
UPDATE menu SET image_url = 'images_1/cholebature.webp' WHERE restaurant_id=12 AND name='Chole Puri';
UPDATE menu SET image_url = 'Images_2/9 McAloo Tikki.jpeg' WHERE restaurant_id=12 AND name='Aloo Paratha';
UPDATE menu SET image_url = 'images_1/PaneerButterMasala.jpg' WHERE restaurant_id=12 AND name='Paneer Tikka';
UPDATE menu SET image_url = 'images_1/classicburger.png' WHERE restaurant_id=12 AND name='Lassi (Sweet)';
UPDATE menu SET image_url = 'Images_2/15 meals.jpeg' WHERE restaurant_id=13 AND name='Full Meals (Veg)';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=13 AND name='Rasam';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=13 AND name='Kootu';
UPDATE menu SET image_url = 'Images_2/2 chicken fried rice.jpeg' WHERE restaurant_id=13 AND name='Ghee Rice';
UPDATE menu SET image_url = 'images_gen/payasam_1787916358390.jpg' WHERE restaurant_id=13 AND name='Payasam';
UPDATE menu SET image_url = 'images_1/idli.webp' WHERE restaurant_id=14 AND name='Ven Pongal';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=14 AND name='Sakkarai Pongal';
UPDATE menu SET image_url = 'Images_2/2 chicken fried rice.jpeg' WHERE restaurant_id=14 AND name='Kara Kuzhambu Rice';
UPDATE menu SET image_url = 'images_1/vada.jpg' WHERE restaurant_id=14 AND name='Vada';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=14 AND name='Kollu Rasam';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=15 AND name='Veg Parotta Set';
UPDATE menu SET image_url = 'Images_2/15 meals.jpeg' WHERE restaurant_id=15 AND name='Full Meals';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=15 AND name='Chapati Kurma';
UPDATE menu SET image_url = 'images_1/background.webp' WHERE restaurant_id=15 AND name='Egg Parotta';
UPDATE menu SET image_url = 'images_1/classicburger.png' WHERE restaurant_id=15 AND name='Lassi';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=16 AND name='Chicken Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=16 AND name='Mutton Biryani';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=16 AND name='Chicken 65';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=16 AND name='Mutton Chukka';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=16 AND name='Chicken Gravy';
UPDATE menu SET image_url = 'images_1/raita.jpg' WHERE restaurant_id=16 AND name='Raita';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=17 AND name='Chettinad Chicken Curry';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=17 AND name='Mutton Sukka';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=17 AND name='Chicken Biryani';
UPDATE menu SET image_url = 'images_1/Fishtikka.jpg' WHERE restaurant_id=17 AND name='Fish Fry';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=17 AND name='Egg Omelette';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=18 AND name='Grilled Chicken Half';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=18 AND name='Chicken Wings (6 Pcs)';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=18 AND name='Peri Peri Chicken';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=18 AND name='Chicken Shawarma';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=18 AND name='Chicken Fried Rice';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=19 AND name='Chettinad Chicken';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=19 AND name='Mutton Curry';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=19 AND name='Chettinad Biryani';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=19 AND name='Pepper Chicken';
UPDATE menu SET image_url = 'images_1/PaneerButterMasala.jpg' WHERE restaurant_id=19 AND name='Neer Mor';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=20 AND name='Crispy Fried Chicken';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=20 AND name='Chicken Burger';
UPDATE menu SET image_url = 'images_1/frenchfries.jpg' WHERE restaurant_id=20 AND name='Loaded Fries';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=20 AND name='Chicken Strips';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=20 AND name='Spicy Wings';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=26 AND name='Royal Chicken Biryani';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=26 AND name='Mutton Tikka';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=26 AND name='Chicken Kebab';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=26 AND name='Firni';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=27 AND name='Mutton Biryani';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=27 AND name='Liver Fry';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=27 AND name='Mutton Pepper Fry';
UPDATE menu SET image_url = 'images_1/misosoup.jpg' WHERE restaurant_id=27 AND name='Bone Soup';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=28 AND name='Chicken Curry Rice';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=28 AND name='Egg Biryani';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=28 AND name='Omelette';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=28 AND name='Mutton Gravy';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=29 AND name='Chicken Biryani';
UPDATE menu SET image_url = 'Images_2/2 chicken fried rice.jpeg' WHERE restaurant_id=29 AND name='Egg Rice';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=29 AND name='Mutton Chops';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=29 AND name='Chicken Soup';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=30 AND name='BBQ Chicken';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=30 AND name='Grilled Mutton Chops';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=30 AND name='Chicken Satay';
UPDATE menu SET image_url = 'images_1/amritsarifish.jpg' WHERE restaurant_id=30 AND name='Grilled Prawns';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=31 AND name='Thalappakatti Mutton Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=31 AND name='Thalappakatti Chicken Biryani';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=31 AND name='Salna';
UPDATE menu SET image_url = 'images_1/raita.jpg' WHERE restaurant_id=31 AND name='Raita';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=32 AND name='Ambur Mutton Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=32 AND name='Ambur Chicken Biryani';
UPDATE menu SET image_url = 'images_1/cholebature.webp' WHERE restaurant_id=32 AND name='Dalcha';
UPDATE menu SET image_url = 'images_1/ChickenCurry.jpg' WHERE restaurant_id=32 AND name='Brinjal Curry';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=33 AND name='Hyderabadi Dum Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=33 AND name='Paradise Chicken Biryani';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=33 AND name='Mirchi Ka Salan';
UPDATE menu SET image_url = 'Images_2/megh double.jpeg' WHERE restaurant_id=33 AND name='Double Ka Meetha';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=34 AND name='Chicken Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=34 AND name='Veg Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=34 AND name='Prawn Biryani';
UPDATE menu SET image_url = 'images_1/raita.jpg' WHERE restaurant_id=34 AND name='Raita';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=35 AND name='Haleem';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=35 AND name='Dum Chicken Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=35 AND name='Mutton Dum Biryani';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=35 AND name='Sheer Khurma';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=36 AND name='Chicken Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=36 AND name='Mutton Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=36 AND name='Veg Biryani';
UPDATE menu SET image_url = 'images_1/classicburger.png' WHERE restaurant_id=36 AND name='Lassi';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=37 AND name='Lucknowi Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=37 AND name='Kolkata Style Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=37 AND name='Hyderabadi Biryani';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=37 AND name='Phirni';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=38 AND name='Chicken Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=38 AND name='Mutton Biryani';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=38 AND name='Salna';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=38 AND name='Boiled Egg';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=39 AND name='Chettinad Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=39 AND name='Mutton Biryani';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=39 AND name='Chicken Tikka';
UPDATE menu SET image_url = 'images_1/raita.jpg' WHERE restaurant_id=39 AND name='Raita';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=40 AND name='Ambur Chicken Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=40 AND name='Ambur Mutton Biryani';
UPDATE menu SET image_url = 'images_1/cholebature.webp' WHERE restaurant_id=40 AND name='Dalcha';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=40 AND name='Sirka Onions';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=41 AND name='Hyderabadi Dum Mutton';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=41 AND name='Dum Chicken Biryani';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=41 AND name='Mirchi Salan';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=41 AND name='Khubani Ka Meetha';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=42 AND name='Express Chicken Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=42 AND name='Egg Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=42 AND name='Veg Biryani';
UPDATE menu SET image_url = 'images_1/onionrings.jpg' WHERE restaurant_id=42 AND name='Onion Raita';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=43 AND name='Nawabi Dum Biryani';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=43 AND name='Mutton Korma';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=43 AND name='Shahi Chicken Biryani';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=43 AND name='Phirni';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=44 AND name='Madurai Chicken Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=44 AND name='Mutton Biryani';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=44 AND name='Coin Parotta';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=44 AND name='Chicken Salna';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=45 AND name='Multi Style Chicken Biryani';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=45 AND name='Veg Biryani Trail';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=45 AND name='Chicken Seekh Kebab';
UPDATE menu SET image_url = 'images_1/raita.jpg' WHERE restaurant_id=45 AND name='Raita';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=46 AND name='Chettinad Chicken Curry';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=46 AND name='Mutton Chukka';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=46 AND name='Pepper Chicken';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=46 AND name='Chettinad Biryani';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=47 AND name='Mutton Sukka';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=47 AND name='Chicken Chettinad';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=47 AND name='Kari Dosa';
UPDATE menu SET image_url = 'images_1/PaneerButterMasala.jpg' WHERE restaurant_id=47 AND name='Neer Mor';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=48 AND name='Chettinad Heritage Thali';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=48 AND name='Paniyaram';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=48 AND name='Chicken Curry';
UPDATE menu SET image_url = 'images_1/kheer.jpg' WHERE restaurant_id=48 AND name='Kavuni Arisi Kheer';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=49 AND name='Ponnusamy Chicken';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=49 AND name='Mutton Biryani';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=49 AND name='Chicken Salna';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=49 AND name='Parotta';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=50 AND name='Kavuni Arisi Dessert';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=50 AND name='Chettinad Chicken Kuzhambu';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=50 AND name='Meen Kuzhambu';
UPDATE menu SET image_url = 'images_gen/appam_stew_1787916343153.jpg' WHERE restaurant_id=50 AND name='Appam';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=51 AND name='Fine Dining Chettinad Thali';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=51 AND name='Signature Chicken Chettinad';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=51 AND name='Mutton Roast';
UPDATE menu SET image_url = 'images_1/coldcoffee.jpg' WHERE restaurant_id=51 AND name='Welcome Drink';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=52 AND name='Kari Dosa (Non-Veg)';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=52 AND name='Mutton Curry';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=52 AND name='Egg Omelette';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=52 AND name='Chicken Biryani';
UPDATE menu SET image_url = 'Images_2/2 chicken fried rice.jpeg' WHERE restaurant_id=53 AND name='Meen Kuzhambhu Rice';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=53 AND name='Pepper Chicken';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=53 AND name='Chettinad Chicken Biryani';
UPDATE menu SET image_url = 'images_1/PaneerButterMasala.jpg' WHERE restaurant_id=53 AND name='Neer Mor';
UPDATE menu SET image_url = 'Images_2/15 meals.jpeg' WHERE restaurant_id=54 AND name='Traditional Chettinad Meals';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=54 AND name='Appam with Chicken Stew';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=54 AND name='Kavuni Arisi';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=54 AND name='Village Style Mutton';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=55 AND name='Village Chicken Kheema';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=55 AND name='Mutton Kheema';
UPDATE menu SET image_url = 'images_1/Fishtikka.jpg' WHERE restaurant_id=55 AND name='Chettinad Fish Fry';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=55 AND name='Parotta';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=56 AND name='Mysore Pak';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=56 AND name='Kaju Katli';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=56 AND name='Masala Dosa';
UPDATE menu SET image_url = 'Images_2/15 meals.jpeg' WHERE restaurant_id=56 AND name='Full Meals';
UPDATE menu SET image_url = 'images_1/background.webp' WHERE restaurant_id=56 AND name='Basundi';
UPDATE menu SET image_url = 'images_1/ChickenCurry.jpg' WHERE restaurant_id=57 AND name='Fish Curry Rice';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=57 AND name='Veg Thali';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=57 AND name='Prawn Masala';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=57 AND name='Crab Masala';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=58 AND name='Plain Dosa';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=58 AND name='Masala Dosa';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=58 AND name='Set Dosa';
UPDATE menu SET image_url = 'images_1/coldcoffee.jpg' WHERE restaurant_id=58 AND name='Filter Coffee';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=59 AND name='Chicken Parotta';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=59 AND name='Veg Parotta Kurma';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=59 AND name='Chicken Curry';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=59 AND name='Egg Dosa';
UPDATE menu SET image_url = 'Images_2/15 meals.jpeg' WHERE restaurant_id=60 AND name='Full Meals';
UPDATE menu SET image_url = 'Images_2/2 chicken fried rice.jpeg' WHERE restaurant_id=60 AND name='Sambar Rice';
UPDATE menu SET image_url = 'Images_2/2 chicken fried rice.jpeg' WHERE restaurant_id=60 AND name='Curd Rice';
UPDATE menu SET image_url = 'images_gen/payasam_1787916358390.jpg' WHERE restaurant_id=60 AND name='Payasam';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=61 AND name='Bajji';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=61 AND name='Chicken Meals';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=61 AND name='Murukku';
UPDATE menu SET image_url = 'images_1/background.webp' WHERE restaurant_id=61 AND name='Bonda';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=62 AND name='Idiyappam';
UPDATE menu SET image_url = 'images_gen/appam_stew_1787916343153.jpg' WHERE restaurant_id=62 AND name='Appam';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=62 AND name='Puttu';
UPDATE menu SET image_url = 'images_1/coldcoffee.jpg' WHERE restaurant_id=62 AND name='Filter Coffee';
UPDATE menu SET image_url = 'Images_2/15 meals.jpeg' WHERE restaurant_id=63 AND name='Banana Leaf Meals';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=63 AND name='Special Thali';
UPDATE menu SET image_url = 'images_gen/payasam_1787916358390.jpg' WHERE restaurant_id=63 AND name='Payasam';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=63 AND name='Rasam';
UPDATE menu SET image_url = 'images_1/idli.webp' WHERE restaurant_id=64 AND name='Pongal';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=64 AND name='Upma';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=64 AND name='Dosa';
UPDATE menu SET image_url = 'images_1/coldcoffee.jpg' WHERE restaurant_id=64 AND name='Filter Coffee';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=65 AND name='Kotthu Parotta';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=65 AND name='Chicken Parotta';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=65 AND name='Veg Kotthu';
UPDATE menu SET image_url = 'images_1/Muttonbiryani.webp' WHERE restaurant_id=65 AND name='Mutton Kotthu';
UPDATE menu SET image_url = 'images_1/Fishtikka.jpg' WHERE restaurant_id=66 AND name='Fish Fry';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=66 AND name='Prawn Masala';
UPDATE menu SET image_url = 'images_1/ChickenCurry.jpg' WHERE restaurant_id=66 AND name='Crab Curry';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=66 AND name='Lobster Thermidor';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=66 AND name='Fish Biryani';
UPDATE menu SET image_url = 'images_1/GarlicNaan.jpg' WHERE restaurant_id=67 AND name='Crab Butter Garlic';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=67 AND name='Prawn Biryani';
UPDATE menu SET image_url = 'images_1/Fishtikka.jpg' WHERE restaurant_id=67 AND name='Fish Fry';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=67 AND name='Prawn Masala';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=68 AND name='Grilled Sea Bass';
UPDATE menu SET image_url = 'images_1/ChickenCurry.jpg' WHERE restaurant_id=68 AND name='Fish Curry';
UPDATE menu SET image_url = 'Images_2/2 chicken fried rice.jpeg' WHERE restaurant_id=68 AND name='Fried Prawns';
UPDATE menu SET image_url = 'images_1/PepperoniPizza.webp' WHERE restaurant_id=68 AND name='Squid Pepper Fry';
UPDATE menu SET image_url = 'images_1/Fishtikka.jpg' WHERE restaurant_id=69 AND name='Seer Fish (Vanjaram) Fry';
UPDATE menu SET image_url = 'images_1/ChickenCurry.jpg' WHERE restaurant_id=69 AND name='Pomfret Fish Curry';
UPDATE menu SET image_url = 'images_1/coldcoffee.jpg' WHERE restaurant_id=69 AND name='Tuna Steak';
UPDATE menu SET image_url = 'images_1/prawn.jpg' WHERE restaurant_id=69 AND name='Prawn Cocktail';
UPDATE menu SET image_url = 'images_1/ChickenCurry.jpg' WHERE restaurant_id=70 AND name='Kerala Fish Curry';
UPDATE menu SET image_url = 'images_1/Crab.jpg' WHERE restaurant_id=70 AND name='Crab Roast';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=70 AND name='Karimeen Pollichathu';
UPDATE menu SET image_url = 'images_1/Fishtikka.jpg' WHERE restaurant_id=70 AND name='Fish Biriyani';
UPDATE menu SET image_url = 'images_1/amritsarifish.jpg' WHERE restaurant_id=71 AND name='Grilled Tiger Prawns';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=71 AND name='Fish Biryani';
UPDATE menu SET image_url = 'images_gen/seafood_pasta_1787916394557.jpg' WHERE restaurant_id=71 AND name='Seafood Platter';
UPDATE menu SET image_url = 'images_1/calamari.webp' WHERE restaurant_id=71 AND name='Calamari';
UPDATE menu SET image_url = 'images_1/Fishtikka.jpg' WHERE restaurant_id=72 AND name='Fish Fry Platter';
UPDATE menu SET image_url = 'images_1/Biryani.jpg' WHERE restaurant_id=72 AND name='Prawn Biryani';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=72 AND name='Crab Masala';
UPDATE menu SET image_url = 'images_1/ChickenCurry.jpg' WHERE restaurant_id=72 AND name='Fish Curry';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=73 AND name='Lobster Bisque';
UPDATE menu SET image_url = 'images_1/GarlicNaan.jpg' WHERE restaurant_id=73 AND name='Tiger Prawn Butter Garlic';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=73 AND name='Sea Bass Fillet';
UPDATE menu SET image_url = 'images_gen/seafood_pasta_1787916394557.jpg' WHERE restaurant_id=73 AND name='Seafood Linguine';
UPDATE menu SET image_url = 'images_1/Fishtikka.jpg' WHERE restaurant_id=74 AND name='Fresh Grilled Fish';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=74 AND name='Prawn Masala Curry';
UPDATE menu SET image_url = 'images_1/paneertikka.jpg' WHERE restaurant_id=74 AND name='Fish Tikka';
UPDATE menu SET image_url = 'images_1/PepperoniPizza.webp' WHERE restaurant_id=74 AND name='Crab Pepper Fry';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=75 AND name='Meen Pollichathu';
UPDATE menu SET image_url = 'images_1/ChickenCurry.jpg' WHERE restaurant_id=75 AND name='Kerala Prawn Curry';
UPDATE menu SET image_url = 'images_gen/appam_stew_1787916343153.jpg' WHERE restaurant_id=75 AND name='Appam';
UPDATE menu SET image_url = 'images_1/Crab.jpg' WHERE restaurant_id=75 AND name='Crab Roast';
UPDATE menu SET image_url = 'Images_2/3 Classic Cheese Burger.jpg' WHERE restaurant_id=76 AND name='Cheese Burst Margherita';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=76 AND name='Chicken Supreme';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=76 AND name='BBQ Chicken';
UPDATE menu SET image_url = 'images_1/GarlicNaan.jpg' WHERE restaurant_id=76 AND name='Garlic Bread';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=76 AND name='Pasta Arabiatta';
UPDATE menu SET image_url = 'images_1/MARGHERITA.jpg' WHERE restaurant_id=77 AND name='Margherita';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=77 AND name='Chicken Pepperoni';
UPDATE menu SET image_url = 'images_1/biriyanihouse.webp' WHERE restaurant_id=77 AND name='Farm House';
UPDATE menu SET image_url = 'images_1/GarlicNaan.jpg' WHERE restaurant_id=77 AND name='Garlic Bread Sticks';
UPDATE menu SET image_url = 'images_1/cheesecake.webp' WHERE restaurant_id=77 AND name='Choco Lava Cake';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=78 AND name='Stuffed Crust Veg';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=78 AND name='Chicken Tikka Pizza';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=78 AND name='Pasta Alfredo';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=78 AND name='Chicken Wings';
UPDATE menu SET image_url = 'images_1/BBQchickenpizza.jpg' WHERE restaurant_id=79 AND name='Smokin Joe Classic Pizza';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=79 AND name='Chicken Overload';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=79 AND name='Veg Pasta';
UPDATE menu SET image_url = 'Images_2/3 Classic Cheese Burger.jpg' WHERE restaurant_id=79 AND name='Cheese Dip';
UPDATE menu SET image_url = 'images_1/MARGHERITA.jpg' WHERE restaurant_id=80 AND name='Wood Fired Margherita';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=80 AND name='Quattro Formaggi';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=80 AND name='Diavola';
UPDATE menu SET image_url = 'images_1/background.webp' WHERE restaurant_id=80 AND name='Bruschetta';
UPDATE menu SET image_url = 'images_1/classicburger.png' WHERE restaurant_id=81 AND name='Classic Margherita';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=81 AND name='Chicken Balsamico';
UPDATE menu SET image_url = 'images_1/tiramisu.jpg' WHERE restaurant_id=81 AND name='Tiramisu';
UPDATE menu SET image_url = 'images_1/GarlicNaan.jpg' WHERE restaurant_id=81 AND name='Garlic Dough Balls';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=82 AND name='Peri Peri Chicken Pizza';
UPDATE menu SET image_url = 'images_1/BBQchickenpizza.jpg' WHERE restaurant_id=82 AND name='BBQ Non-Veg Pizza';
UPDATE menu SET image_url = 'images_1/BBQchickenpizza.jpg' WHERE restaurant_id=82 AND name='Mac and Cheese Pizza';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=82 AND name='Chicken Wings';
UPDATE menu SET image_url = 'images_1/MARGHERITA.jpg' WHERE restaurant_id=83 AND name='Thin Crust Margherita';
UPDATE menu SET image_url = 'images_1/PaneerButterMasala.jpg' WHERE restaurant_id=83 AND name='Paneer Tikka Pizza';
UPDATE menu SET image_url = 'images_1/BBQchickenpizza.jpg' WHERE restaurant_id=83 AND name='Fusion Mexican Pizza';
UPDATE menu SET image_url = 'Images_2/3 Classic Cheese Burger.jpg' WHERE restaurant_id=83 AND name='Cheese Overload';
UPDATE menu SET image_url = 'images_1/MARGHERITA.jpg' WHERE restaurant_id=84 AND name='Neapolitan Margherita';
UPDATE menu SET image_url = 'images_1/classicburger.png' WHERE restaurant_id=84 AND name='Pepperoni Classic';
UPDATE menu SET image_url = 'Images_2/truffles.avif' WHERE restaurant_id=84 AND name='Mushroom Truffle';
UPDATE menu SET image_url = 'images_1/tiramisu.jpg' WHERE restaurant_id=84 AND name='Tiramisu';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=85 AND name='Cheese Burst Chicken';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=85 AND name='Loaded Veg Feast';
UPDATE menu SET image_url = 'Images_2/3 Classic Cheese Burger.jpg' WHERE restaurant_id=85 AND name='Triple Cheese Margherita';
UPDATE menu SET image_url = 'images_1/GarlicNaan.jpg' WHERE restaurant_id=85 AND name='Stuffed Garlic Bread';
UPDATE menu SET image_url = 'images_1/chickenburger.jpg' WHERE restaurant_id=86 AND name='McAloo Tikki Burger';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=86 AND name='McSpicy Chicken Burger';
UPDATE menu SET image_url = 'images_1/frenchfries.jpg' WHERE restaurant_id=86 AND name='French Fries (Large)';
UPDATE menu SET image_url = 'Images_2/9 McFlurry.jpeg' WHERE restaurant_id=86 AND name='McFlurry Oreo';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=86 AND name='Chicken McNuggets (6 Pcs)';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=87 AND name='KFC Original Fried Chicken (2 Pcs)';
UPDATE menu SET image_url = 'images_1/chickenburger.jpg' WHERE restaurant_id=87 AND name='Zinger Burger';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=87 AND name='Hot Wings (6 Pcs)';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=87 AND name='Coleslaw';
UPDATE menu SET image_url = 'Images_2/10 Pepsi.jpeg' WHERE restaurant_id=87 AND name='Pepsi (Large)';
UPDATE menu SET image_url = 'images_1/chickenburger.jpg' WHERE restaurant_id=88 AND name='Whopper Burger';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=88 AND name='Crispy Chicken Burger';
UPDATE menu SET image_url = 'images_1/onionrings.jpg' WHERE restaurant_id=88 AND name='Onion Rings';
UPDATE menu SET image_url = 'images_1/chickenburger.jpg' WHERE restaurant_id=88 AND name='Veg Burger';
UPDATE menu SET image_url = 'Images_2/subway.avif' WHERE restaurant_id=89 AND name='Subway Club';
UPDATE menu SET image_url = 'Images_2/4 Apricot Delight.jpeg' WHERE restaurant_id=89 AND name='Veggie Delight';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=89 AND name='Chicken Teriyaki';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=89 AND name='Cookie';
UPDATE menu SET image_url = 'images_1/coldcoffee.jpg' WHERE restaurant_id=90 AND name='Steamed Momos (6 Pcs)';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=90 AND name='Chicken Momos (6 Pcs)';
UPDATE menu SET image_url = 'Images_2/2 chicken fried rice.jpeg' WHERE restaurant_id=90 AND name='Pan Fried Momos';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=90 AND name='Thukpa';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=91 AND name='Chicken Kathi Roll';
UPDATE menu SET image_url = 'images_1/PaneerButterMasala.jpg' WHERE restaurant_id=91 AND name='Paneer Roll';
UPDATE menu SET image_url = 'images_1/springrolls.jpg' WHERE restaurant_id=91 AND name='Egg Roll';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=91 AND name='Veg Frankie';
UPDATE menu SET image_url = 'images_1/chickenburger.jpg' WHERE restaurant_id=92 AND name='Shack Burger';
UPDATE menu SET image_url = 'images_1/chickenburger.jpg' WHERE restaurant_id=92 AND name='Smoke Shack Burger';
UPDATE menu SET image_url = 'images_1/Milkshake.jpg' WHERE restaurant_id=92 AND name='Concrete Shake';
UPDATE menu SET image_url = 'images_1/frenchfries.jpg' WHERE restaurant_id=92 AND name='Shack Fries';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=93 AND name='Pani Puri (6 Pcs)';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=93 AND name='Bhel Puri';
UPDATE menu SET image_url = 'images_1/background.webp' WHERE restaurant_id=93 AND name='Sev Puri';
UPDATE menu SET image_url = 'images_1/Baklava.jpg' WHERE restaurant_id=93 AND name='Dahi Puri';
UPDATE menu SET image_url = 'images_1/MasalaDosa.webp' WHERE restaurant_id=93 AND name='Masala Corn';
UPDATE menu SET image_url = 'images_1/chickenburger.jpg' WHERE restaurant_id=94 AND name='Classic Five Guys Burger';
UPDATE menu SET image_url = 'images_1/burgerbarn.jpg' WHERE restaurant_id=94 AND name='Bacon Cheeseburger';
UPDATE menu SET image_url = 'images_1/frenchfries.jpg' WHERE restaurant_id=94 AND name='Loaded Fries';
UPDATE menu SET image_url = 'images_1/Milkshake.jpg' WHERE restaurant_id=94 AND name='Vanilla Milkshake';
UPDATE menu SET image_url = 'Images_2/7 Tacos.jpeg' WHERE restaurant_id=95 AND name='Crunchy Taco';
UPDATE menu SET image_url = 'Images_2/7 Tacos.jpeg' WHERE restaurant_id=95 AND name='Soft Taco (Veg)';
UPDATE menu SET image_url = 'Images_2/7 Nachos.jpeg' WHERE restaurant_id=95 AND name='Nachos';
UPDATE menu SET image_url = 'images_1/burgerbarn.jpg' WHERE restaurant_id=95 AND name='Crunchwrap Supreme';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=96 AND name='Rasgulla (4 Pcs)';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=96 AND name='Mathura Peda';
UPDATE menu SET image_url = 'images_1/background.webp' WHERE restaurant_id=96 AND name='Kaju Katli';
UPDATE menu SET image_url = 'images_1/Baklava.jpg' WHERE restaurant_id=96 AND name='Sev Mixture';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=97 AND name='Crispy Fried Chicken';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=97 AND name='Chicken Wrap';
UPDATE menu SET image_url = 'images_1/burgerbarn.jpg' WHERE restaurant_id=97 AND name='Veg Wrap';
UPDATE menu SET image_url = 'images_1/frenchfries.jpg' WHERE restaurant_id=97 AND name='Seasoned Fries';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=98 AND name='Chicken Fried Rice';
UPDATE menu SET image_url = 'Images_2/Chicken Noodles 2.jpg' WHERE restaurant_id=98 AND name='Veg Hakka Noodles';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=98 AND name='Chicken Manchurian';
UPDATE menu SET image_url = 'images_1/springrolls.jpg' WHERE restaurant_id=98 AND name='Spring Rolls (4 Pcs)';
UPDATE menu SET image_url = 'images_1/vada.jpg' WHERE restaurant_id=99 AND name='Vada Pav';
UPDATE menu SET image_url = 'images_1/pizzacorner.webp' WHERE restaurant_id=99 AND name='Corn Sandwich';
UPDATE menu SET image_url = 'images_1/0_Pasta.png' WHERE restaurant_id=99 AND name='Pav Bhaji';
UPDATE menu SET image_url = 'images_1/Arrabbiata.webp' WHERE restaurant_id=99 AND name='Misal Pav';
UPDATE menu SET image_url = 'images_1/chickenburger.jpg' WHERE restaurant_id=100 AND name='Veg Burger';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=100 AND name='Chicken Burger';
UPDATE menu SET image_url = 'images_1/PaneerButterMasala.jpg' WHERE restaurant_id=100 AND name='Paneer Roll';
UPDATE menu SET image_url = 'images_1/Chicken-Biryani.webp' WHERE restaurant_id=100 AND name='Chicken Roll';
UPDATE menu SET image_url = 'images_1/frenchfries.jpg' WHERE restaurant_id=100 AND name='French Fries';
